### ISSUE TITLE
Widewine CDM extraction error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 34

### ISSUE THREAD

**Issue by optimist10150** [emilsvennesson/script.module.inputstreamhelper#276]
### My Environment:
Operating system version/name: Raspbian Buster with Kodi Leia 18
Device model: Raspberry Pi 4 Model B

### Description of the bug:
When I start the Netflix AddOn and choose any movie it asks to install Widewine. Everything is working just fine until it wants to extract Widevine CDM.
After a short time the following error message shows up: **UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 79: ordinal not in range(128)**
It's the same with Amazon Prime (from Sandmann79 repository).

Before I activated the AddOn I did the following steps:
sudo apt update
sudo apt upgrade
sudo apt install kodi kodi-peripheral-joystick kodi-pvr-iptvsimple kodi-inputstream-adaptive kodi-inputstream-rtmp
sudo apt install build-essential python-pip python-dev libffi-dev libssl-dev libnss3
sudo pip install setuptools wheel pycryptodomex

### Debug log:
The **debug log** can be found from this link:
https://paste.kodi.tv/sekusalari

Thanks for your help!

**Comment by horstle** [comment]
Please install [this version](https://github.com/horstle/script.module.inputstreamhelper/archive/unicode.zip) and post another debug log.

I think that should fix the unicode error, but the real problem is, that the losetup command failed. The reason for that might be that you don't have passwordless sudo enabled for the user running kodi. In that case either enable it or you could test [this change](https://github.com/horstle/script.module.inputstreamhelper/archive/udisksctl_no_sudo.zip).

**Comment by mediaminister** [comment]
This fixes indeed a possible unicode error, I created a pull request from your unicode branch: https://github.com/emilsvennesson/script.module.inputstreamhelper/pull/279
