### ISSUE TITLE
Widevine cdm extraction stuck

### ISSUE THREAD

**Issue by giovariot** [emilsvennesson/script.module.inputstreamhelper#325]
I installed an add-on which requires widevine-cdm on LibreElec on my Raspberry Pi 4, it correctly opens the EULA window and warns you it'll have to download a 3.1G ChromeOS image. It correctly downloads it, then starts extracting and the funny thing is that the more the progress bar goes on the slower that progress becomes.

I tried a few times for an hour or so, tonight I tried leaving it working for around 12h and this morning it was *exactly* where I left it yesterday night. I checked my [kod.log](https://gist.github.com/giovariot/30859d41e2b5c222b36ad6c109224f9f) but couldn't find anything wrong.

I also read this [comment](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/292#issuecomment-596257643) in issue #292, I tried to run it but being a complete and utter noob this is what I get:
``Traceback (most recent call last):
  File "load-chromium-widevine.py", line 137, in <module>
    os.remove("recovery.conf")
FileNotFoundError: [Errno 2] No such file or directory: 'recovery.conf'``

Does anyone know where I can get the right recovery.conf? Is it the one suggested [here](https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/26#issuecomment-392329000) on #26 ?

Is there any way I can get widevine to install? I also tried copying libwidevinecdm.so to .kodi/cdm/. but I'm told the system needs to update widevine cdm and sends me back to downloading the chromeos image. I know that's from not adding the correct configuration into the json file, but I really don't know what to do.

Thanks in advance

**Comment by horstle** [comment]
If you placed the correct libwidevinecdm.so in ~/.kodi/cdm, you can disable inputstreamhelper through its settings page (not through the information window!).
After that it should work, but I'd rather find out where the problem is (I guess somehow `unzip_thread` stays alive forever?) so please enable debug logging (in Settings > System > Logging) and upload a debug log of another try.

**Comment by giovariot** [comment]
Thank you for your help.

I'll do it as soon as I can. I managed to fix the problem with the #292 script and manually copying the files created on my pc on .kodi/cdm

**Comment by florianjacob** [comment]
Had the same issue and could reproduce multiple times, until I turned on the Debug Log, then everything worked flawlessly. xD

**Comment by horstle** [comment]
@giovariot The logging behaviour was changed recently. If the same thing happens to you, as to @florianjacob , please try the current master branch with debug logging disabled. Maybe the resulting normal log gives a hint where the problem lies, or the issue disappeared for whatever reason.

**Comment by hierklapptnix** [comment]
I have got that problem, too.

It's on my RPi3 Libreelec 9.2.1 fresh out-of-the-box installation (english) as well as on my normal RPi4 machine with Libreelec 9.2.1 (german / updated from 9.2). Both are on 32GB SD cards. On the RPi3 I just completed the first steps and installed TV NOW from Kodinerds. It requires Widevine and starts the installation.

It happens with ISH 0.4.5 and 0.4.6. Difference is that system load seems not to go through the roof with 0.4.6 but it always stops at approx. 90%-95% in both cases.

Cancel does not help (or I'm not waiting long enough. It tells "cancelling" but time still runs on).

I have attached one normal and one debug run log. Maybe sombody can see the cause.
The occasional cursor-up-key is just because of the screensaver.

Hope I did nothing wrong. Is my first time here...

[kodi-debug.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4565222/kodi-debug.log)
[kodi.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4565223/kodi.log)

**Comment by hierklapptnix** [comment]
Ok. Not sure if I've done this correctly.

I have downloaded the .zip of horstle:unzip and replaced my inputstreamhelper addon (/storage/.kodi/addons) by overwriting them with scp.

Now I get the countdown for downloading and extracting as expected. It's quite precise for download but somewhat unusable for extraction as it always goes up and down.

The result was that extraction now ends but there's the kodi error popup and Widevine is not installed.

Here is a debug log:

[kodi-debug_horstle-unzip.log](https://github.com/emilsvennesson/script.module.inputstreamhelper/files/4567614/kodi-debug_horstle-unzip.log)

Sorry I'm late. Just have seen there's the 0.4.7. Have not tried it and am posting this anyway.

**Comment by horstle** [comment]
You now encountered (more or less) #333 ... @mediaminister is working on it. But this issue seems to be resolved.
