### ISSUE TITLE
Odroid C2 Unable to load shared library

### ISSUE THREAD

**Issue by rgainza** [emilsvennesson/script.module.inputstreamhelper#35]
```log
19:33:54.179 T:3975140208   ERROR: AddOnLog: InputStream Adaptive: Unable to load widevine shared library (/storage/.kodi/cdm/libwidevinecdm.so)
```

Your script downloads the widevine module. No problem there, but for some reason I can't get that module to work. The macleod script worked for it without any problems so I thought it was the same structure as the RPi. 

Which recovery OS image is the best for the Odroid C2?

**Comment by deorder** [comment]
Temp fix for the ARM version. 7zip or another archive tool that supports filesystem images required.

Go to: https://cros-updates-serving.appspot.com/#speedy

Click `67` on the line with the codename `Speedy`. It will download an older version of Chrome OS.
Direct link: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_10575.58.0_daisy-spring_recovery_stable-channel_spring-mp-v3.bin.zip

Open the archive, open the `.bin` file and then open the `ROOT-A.img` file. You will several directories.

Go to `\opt\google\chrome\`. In there you will find the file `libwidevinecdm.so`.

Extract the file `libwidevinecdm.so` and copy it to your Kodi home directory in `~/.kodi/userdata/addon_data/script.module.inputstreamhelper/cdm` or similar (instead of overwriting you can backup the already existing one).

Restart Kodi

**Comment by rgainza** [comment]
Thank you!

**Comment by rspierenburg** [comment]
I download the file, extract the zip to a .bin, but when I try to extract the .bin file it tells me there is an error in the file.  I've downloaded both from the direct link and the actual page.  Is there anywhere else I can get the libwidevinecdm.so file?

**Comment by rgainza** [comment]
I don't think it's allowed to share the .so file openly according to the license (copying not allowed)? 

Just use the SSH and follow the instructions. 
https://help.vivaldi.com/article/raspberry-pi/#drm-and-flash

You could create a bash script:

#!/bin/sh
CHROMEOSR="https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_10575.58.0_daisy-spring_recovery_stable-channel_spring-mp-v3.bin.zip"
wget $CHROMEOSR
unzip $(basename $CHROMEOSR)
LOOPD=$(losetup -f)
sudo losetup -P $LOOPD $(basename $CHROMEOSR .zip)
mkdir chromeos
sudo mount -o ro ${LOOPD}p3 chromeos
cp chromeos/opt/google/chrome/libwidevinecdm.so  ~/.kodi/cdm
sudo umount chromeos
rmdir chromeos
sudo losetup -d ${LOOPD}
rm -vi $(basename $CHROMEOSR) $(basename $CHROMEOSR .zip)

Somebody else can probably make it better.

**Comment by deorder** [comment]
This is now fixed. The latest Milhouse LibreELEC testbuild already has the fix.

**Comment by matthuisman** [comment]
@holzfuss

Widevine appears to no longer work in KODI 17 at all.
You will need to update to KODI 18 (LibreELEC Alpha)

**Comment by holzfuss** [comment]
It did work on Kodi 17, LE 8.2.5, I.A 2.0.20, so why doesn't it work any more?
Did DAZN and SKY change anything? Otherwise this would make no sense...

**Comment by rgainza** [comment]
Widevine versions were blacklisted by Google. The newer versions aren't supported by the inputstream that the Kodi v17 is using. Simple as that.

**Comment by holzfuss** [comment]
So Google did change something. Thanks for this clear explanation.
Waiting for a fix by peak3d for Kodi 17 :-)

**Comment by matthuisman** [comment]
@holzfuss 
There isn't a "fix" for KODI 17.

It simply needs a later version of the inpustream.adaptive add-on to run.
However, later versions of that add-on require code changes in KODI itself.
These changes are only in KODI 18.
They won't be back-ported as there are no-more KODI 17 versions to be released.

The fix is to switch to KODI 18 Beta or wait for KODI 18 Stable

**Comment by holzfuss** [comment]
Well, I have no idea how much time it would take to backport the necessary code to KODI 17.
But as long as KODI 18/LE 9 is that far away from being stable, it would not be the worst idea...

Waiting for KODI 18/LE 9 to get stable... :/

**Comment by matthuisman** [comment]
Even if you did back-port the code yourself, they aren't releasing any more versions of KODI (no 17.7).
So you'd need to compile your own LE using your modified KODI source.

I don't think 18 is that far away.
I'd guess one more Beta.
Then RC1 and RC2.
Then 18.0.
Then you need to wait for LE to go stable.

**Comment by stsichler** [comment]
@holzfuss 
> Well, I have no idea how much time it would take to backport the necessary code to KODI 17

I do have. :) It's pretty simple and since today, I have Widevine working again in Kodi 17.6 on my good old Odroid U3. 
See my feature request <https://github.com/peak3d/inputstream.adaptive/issues/193>

**Comment by holzfuss** [comment]
So, we only need some changes in the inputstream.adaptive plugin?
@peak3d, @stsichler That would be f*cking awesome.

LE is still Alpha5 since 17th of September...it is probably months away from being stable.

**Comment by dagwieers** [comment]
I am not sure, but I don't think any activity is to be expected for Kodi Krypton.
Your best bet is to move to Kodi Leia.

**Comment by dagwieers** [comment]
I am tempted to close this issue, as I don't know what to do or expect from this conversation.
Feedback appreciated ;-)

**Comment by dagwieers** [comment]
I am going to close this now. **inputstreamhelper** (or rather Widevine) is only supported on Kodi 18 and newer. This is out of our control currently.

Feel free to report any feedback related to this issue here though.
