### ISSUE TITLE
Shouldn't InputStream Helper be a Service rather than a Program add-on?

### ISSUE THREAD

**Issue by CiNcH83** [emilsvennesson/script.module.inputstreamhelper#426]
_InputStream Helper_ appears in the _Add-ons > Program add-ons_ menu in Kodi which is a bit annoying. Isn't InputStream Helper a _Service_ add-on rather than a _Program_ add-on?

**Comment by dagwieers** [comment]
InputStream Helper is in fact a library. But is has a settings page, and because a library with a settings page is not easy to find (in order to change settings) we decided on 2 things:
- Add an API for other add-ons to call from their settings
- Have an add-on entry script to easily go to the settings (program)

In short: ISH is not a service, but not really a program either.
