### ISSUE TITLE
Any way to disable widevine update checking?

### ISSUE THREAD

**Issue by NoahJelen** [emilsvennesson/script.module.inputstreamhelper#448]
Is there any possible way to disable checking for updates for widevine? Any time I open a video in the Netflix addon, I get a pop-up saying "An update is available for widevide cdm". How the hell do I disable this pop up?

**Comment by dagwieers** [comment]
Yes, see the add-on settings. If you disable the add-on, it will not perform any checking.

Beware that if you don't regularly download a new Widevine version, your Kodi will stop working correctly for DRM content (would have happened twice in the past and will very soon in the future).

**Comment by sorin-pop** [comment]
"Beware that if you don't regularly download a new Widevine version, your Kodi will stop working correctly for DRM content"

Actually my experience rather shows the opposite, that it all tends to get broken and f_cked up if I update Widevine (say yes in that popup). So I rather stay on the safe side now as far as I can, and always choose not to update as much as possible.

**Comment by dagwieers** [comment]
Until your Widevine version gets revoked...

The new Widevine version that "broke" Kodi on ARM recently was slated to be revoked by 2021-05-31. But Google did not enforce that deadline yet, luckily. Because Kodi distributions were not 100% ready at the short notice.

But feel free to disable it, there is no good solution for Widevine on ARM at this time and you can blame Google for this situation.

**Comment by dagwieers** [comment]
Closing this issue as one can disable ISH from the add-on settings.
