### ISSUE TITLE
v0.5.9 release distribution failed

### ISSUE THREAD

**Issue by raphaelbrugier** [emilsvennesson/script.module.inputstreamhelper#507]
Hello,

I was trying to update to 0.5.9 and noticed it was not available on the official Kodi mirrors.

Looking at the built workflow for the release, it seems the step to publish the archive to the mirror has failed.
See https://github.com/emilsvennesson/script.module.inputstreamhelper/runs/5652332289?check_suite_focus=true

**Comment by mediaminister** [comment]
I fixed the automatic addon submission. There was a problem with the git protocol.
```
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information
```

The automatic PR's are waiting for review at https://github.com/xbmc/repo-scripts/pulls

**Comment by raphaelbrugier** [comment]
Awesome, thank you!

**Comment by raphaelbrugier** [comment]
@mediaminister Have you noticed that the automated PR on the Kodi repo has failed as well?
See https://github.com/xbmc/repo-scripts/pull/2244

**Comment by mediaminister** [comment]
@raphaelbrugier Yes, I know, it's only a temporary error because we submit the new version of InputStreamHelper for Kodi 17/18 and Kodi 19 at the same time. The version checker complains about the upgradeability between these Kodi versions.
But from the moment the new version of InputStreamHelper for Kodi 19 is released, the error doesn't make sense anymore.

The version for Kodi 19 Matrix is already released: https://mirrors.kodi.tv/addons/matrix/script.module.inputstreamhelper/

So, the version for Kodi 17/18 will definitely follow.
https://mirrors.kodi.tv/addons/krypton/script.module.inputstreamhelper/
