### ISSUE TITLE
Can't play drm content on kodi. Kodi logs attached.

### ISSUE THREAD

**Issue by auau237** [emilsvennesson/script.module.inputstreamhelper#522]
Please help me. I can't play drm content on kodi. I am attaching all kodi logs. Thank you
![1](https://user-images.githubusercontent.com/99367816/195201412-820d6ec8-769d-4462-94bc-10eae3796e81.png)
![b](https://user-images.githubusercontent.com/99367816/195201418-fa60a240-40fa-49c6-bbf1-a134aeb15a82.png)
![c](https://user-images.githubusercontent.com/99367816/195201422-27396324-9737-439b-a3e7-bcfe43ef2acf.png)
![d](https://user-images.githubusercontent.com/99367816/195201428-da907824-fa97-40ee-a6c9-a856d93ed86b.png)
![e](https://user-images.githubusercontent.com/99367816/195201435-b6c860a3-5680-4279-addf-bf7309152190.png)

**Comment by auau237** [comment]
On Kodi, under "Add-on"-"Program addons"- "inputstream helper"-"debug", it reads: 

"Install Widevine from: https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14092.77.0_veyron-fievel_recovery_stable-channel_fievel-mp.bin.zip". 

I downloaded that .zip file. After unzipping it, it has a 2.32 GB .bin file with the same name. What can I do with it? How do I install Widevine on kodi from this .bin file? Anyone willing to help me, please?

**Comment by horstle** [comment]
> "Add-on"-"Program addons"- "inputstream helper"-"debug",

Did it work before? If so, go there and choose "Restore WIdevine library" and then choose the highest version number it offers.

If it did not work before, or this doesn't help, please provide a proper debug log, instead of screenshots of a part of the log...

**Comment by horstle** [comment]
> nvidia shield tv running full android oreo.

That's for example some important information, which would have been in the logfile.

On Android devices, most of inputstreamhelpers functionality is disabled, since they have the widevine library integrated into the system (and even if not, there is nothing we can do). So whatever issue you have, does not belong here. Maybe try the [Kodi forum](https://forum.kodi.tv/) or the [inputstream.adaptive Github page](https://github.com/xbmc/inputstream.adaptive).

They will most probably also want to have the logfile. [Here](https://kodi.wiki/view/Log_file) you can check where to find it and get more information on how to provide a debug log properly.
