### ISSUE TITLE
Feature requests for more expert control

### ISSUE THREAD

**Issue by CastagnaIT** [emilsvennesson/script.module.inputstreamhelper#537]
I am currently involved in the ISAdaptive project that its the only one that support this add-on,
i noticed these limitations on your add-on where it could be more feature-rich
to facilitate development for us in the Kodi Team as well, not only final users

Currently more times i have to do all the operations (install/copy/replace widevine) manually and then download all widewine versions locally and use webbrowser to get new versions etc... always manually or as workaround i have to install an addon that integrate ISH just to run Widevine installation...
so having some improvement on this aspect would be useful

Mainly two requests:

1) Have a way to install CDM from ISH settings, atm its mandatory to have a video add-on that integrate ISH without it your add-on is totally useless. When we developing/debug usually we dont always install video add-ons, so having a way to manually install CDM from expert settings would be very useful to us

2) Have a way to install choosable CDM versions available on the google server, this is not available for all platforms i know, but for supported platforms its must have. The backup functionality is interesting, but totally useless when you have an empty Kodi system

Practically in the expert settings i suggest having:
- Install CDM (allow install CDM without depending from addons, where allow to choose the version, last version pre-selected, this will also replace possible previous installation with selected version) disable this menu to unsupported platforms, at least support common platform of https://dl.google.com/widevine-cdm/versions.txt
- Re-install CDM (unchanged)
- Remove CDM (unchanged)
- Restore CDM (unchanged)

**Comment by horstle** [comment]
> 1. Have a way to install CDM from ISH settings, atm its mandatory to have a video add-on that integrate ISH without it your add-on is totally useless. When we developing/debug usually we dont always install video add-ons, so having a way to manually install CDM from expert settings would be very useful to us

This can already be done with the (Re)install option. That's why the "Re" is in brackets. Basically what it does is get the Widevine library, put it in the backup directory and depending on the platform either link or copy it to the cdm directory. In that last step the current lib gets overwritten if it exists, since we assume it had been installed in the same way, so we have a backup.

> 2. Have a way to install choosable CDM versions available on the google server, this is not available for all platforms i know, but for supported platforms its must have. The backup functionality is interesting, but totally useless when you have an empty Kodi system

I remember there were plans to implement something like that, but somehow it was forgotten. I think that should be fairly simple on all x86 platforms as well as ARM Macs, so basically all except Linux ARM. For Linux ARM there already is an option to specify a local Chrome OS image or a URL pointing to a Chrome OS image to extract the Widevine library from, I think that's all we can do there.

**Comment by CastagnaIT** [comment]
> This can already be done with the (Re)install option

the problem is that the "re-install" setting button is disabled, or maybe you are meaning that can be implemented on existing one,
anyway for me no problem just have the possibility

**Comment by horstle** [comment]
That setting should only be disabled if inputstream.adaptive is disabled, although I can't tell you right now why we need inputstream.adaptive enabled to install widevine.

**Comment by horstle** [comment]
You can test the zips in #538, but the (Re)install setting will still be disabled, if it is right now.
