### ISSUE TITLE
How to properly install on Raspberry Pi OS (4B, 64bit)

### ISSUE THREAD

**Issue by mimre25** [emilsvennesson/script.module.inputstreamhelper#556]
Hi,

I previously had `OSMC` installed on my raspberry pi 4B and I could watch DRM content without any problem. 
Now, I've switched to 64 bit Raspberry Pi OS (version from December 2023) and it doesn't really work.\
I can start playing DRM content, but I just get some mono-duo color blocks on the screen... no real picture of the stream.

I have `libwidevinecdm0` install but `inputstreamhelper` doesn't seem to find it.
The configuration says that there is no version installed and the option to install `widevine` can't be selected/clicked.

I've also tried to install the 32 bit version of the library but to no avail.

Do you have any guide on how to install this properly on a fresh 64-bit Raspberry Pi OS?

**Comment by horstle** [comment]
inputstreamhelper ignores the `libwiedvinecdm0` package, since that may not have the latest version of widevine.

Without a debug log I can only guess what's wrong. Do you have the latest version of `kodi` and `kodi-inputstream-adaptive` installed? In that case just try to play some encrypted stream using an addon which uses inputstreamhelper and it will ask you i it should install widevine.

**Comment by mimre25** [comment]
So turns out I didn't have `kodi-inputstream-adaptive` installed - I installed it today and it all works fine. :slightly_smiling_face:
