### ISSUE TITLE
Stuck on old widevine after canceling first run hotfix

### ISSUE THREAD

**Issue by cache-sk** [emilsvennesson/script.module.inputstreamhelper#77]
When user hit cancel on forced widevine update on first run ("i don't have time for this now"), he stays on old widevine.
Workaround for this is manual edit "version" in settings.xml to "0" (for example).

**Comment by dagwieers** [comment]
From an implementation point of view this makes sense, there is only one first-run detection. A second run would not be a first run ;-) If we wouldn't do it like this, it would have to check every time which defeats the purpose.

We would like to have a settings menu with the option to upgrade, downgrade, remove or select a CDM (planned for v0.5.0), but that means that add-ons have to add a reference to this settings menu because a script/module plugin is not listed in your add-on list, so users would not be able to find the inputstreamhelper settings :-(

We still need to have a discussion related to this. I don't see a good option in general because of the way this mechanism works.

**Comment by dagwieers** [comment]
In the past the `WIDEVINE_UPDATE_INTERVAL_DAYS` was set to 1 day, which looks perfect, but actually means that every user will have a Widevine update the same day it is released (within 24h).

And if a broken/incompatible Widevine would be released (which happened before) all users are immediately impacted. The previous value of `WIDEVINE_UPDATE_INTERVAL_DAYS` was 30 days (so roughly 3% of our users would get an update, every day), which is potentially problematic as the advance warning for CDM revocation was less than 45 days in July. If that falls below our interval, our users would be affected too. That is why we decided to turn it down to 14 days, about 7% of our users will be impacted per day.

**Comment by dagwieers** [comment]
Closed by #91
